// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class   DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
    
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       // case TargetPlatform.iOS:
//       //   return ios;
     
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//  static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB27LBFGKY-6QVB8x1NhXW6C9MEc2osRAk',
//     appId: '1:386639720274:android:5bf256e8211d9938da148b',
//     messagingSenderId: '386639720274',
//     projectId: 'gutargoo-a8707',
//     storageBucket: 'gutargoo-a8707.firebasestorage.app',
//   );

//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyA5wc8-Z4SaDlp58dGWNL3juRx5qm-A6t4',
//   //   appId: '1:564482096190:ios:2d92edf3ea518f9919256f',
//   //   messagingSenderId: '564482096190',
//   //   projectId: 'status-1ebc7',
//   //   storageBucket: 'status-1ebc7.firebasestorage.app',
//   //   androidClientId: '564482096190-5ijb6ukc2fgbivm9tn9p395tkrp0024r.apps.googleusercontent.com',
//   //   iosClientId: '564482096190-g84jd64lrd8be4t01709sup8qadqg6gv.apps.googleusercontent.com',
//   //   iosBundleId: 'com.gutargooproo.application',
//   // );

// }
